apiVersion: 1
datasources:
  - name: Ecommerce Warehouse
    uid: P963A8D4C4F9E4D1A
    type: postgres
    access: proxy
    url: postgres:5432
    user: dw_user
    secureJsonData:
      password: dw_password
    jsonData:
      database: warehouse
      sslmode: disable
      postgresVersion: 16
      timescaledb: false
    isDefault: true
